### ISSUE TITLE
Vagrant utopic64 base box not accessible

### ISSUE THREAD

**Issue by tommyziegler** [zutherb/AppStash#28]
Hi Bernd,

nachdem ich vor ein paar Wochen deinen Talk im Hamburger Codecentric Bure gehen habe wollte ich es mal ausprobieren und habe jetzt festgestellt das die Vagrant Base Box 'utopic64' nicht erreichbar ist.

Könntest du das fixen?

Thx Tommy

**Comment by zutherb** [comment]
Hallo Tommy,
wenn es dir nur darum geht die Anwendung zu laufen zu bekommen, dann nimmt lieber Docker. Ich hoffe ich habe unter dem Compose-Ordner alles beschrieben, was du brauchst um das zu machen. (https://github.com/zutherb/AppStash/blob/master/compose/README.md)

Die Vagrantfiles brauchst du eigentlich nur für die Deployment-Pipeline und den Elk-Stack das habe ich noch nicht vollständig zu compose rüber migriert. Aber wenn ich das nächste mal Zeit habe, kümmere ich mich drum das zu fixen.

Danke für Reporten
BErnd

**Comment by zutherb** [comment]
Hi Tommy,

die Vagrant Files sollten wieder funktionieren. 

Danke für Reporten
Bernd
